services:
  chrome:
    build:
      context: .
      dockerfile: Dockerfile
    image: vnc-chromium-gpu
    gpus: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      - "5900:5900"
    volumes:
      - ./chrome-profile:/data/chrome-profile
    stdin_open: true
    tty: true